contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    path('<int:contact_id>/', views.contact, name='contact'),
    path('', views.index, name='index' ),
    
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contact.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self) -> str:
        return self.name
    
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'


class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

contact/views/contact_views.py
from django.shortcuts import render, get_object_or_404
from contact.models import Contact

def index(request):
    contacts = Contact.objects.filter(show=True).order_by('-id')
    context = {
        'contacts':contacts,
    }
    return render(
        request,
        'contact/index.html',
        context
    )


def contact(request, contact_id):
    single_contact = get_object_or_404(Contact, pk=contact_id, show=True )
    context = {'contact':single_contact}
    return render(request, 'contact/contact.html', context)

contact/templates/contact/contact.html
{% extends 'global/base.html' %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{contact.first_name}} {{ contact.last_name }}
        </h1>
        <p>ID:</b> {{contact.id }}</p>
        <p>Email:</b> {{contact.email }}</p>
        <p>Phone:</b> {{contact.phone }}</p>
        <p>Created Date:</b> {{contact.created_date}}</p>
        <p>Description:</b> {{contact.description }}</p>
        <p>Category:</b> {{contact.category.name }}</p>
        
    </div>
{% endblock content %}

contact/templates/contact/index.html
{% extends "global/base.html" %}

{% block content %}
<div class="responsive-table">
    <table class="contacts-table">
        <caption class="table-caption">
            Contacts
        </caption>
        <thead>
            <tr class="table-row table-row-header">
                <th class="table-header">ID</th>
                <th class="table-header">First Name</th>
                <th class="table-header">Last Name</th>
                <th class="table-header">Phone</th>
                <th class="table-header">Email</th>
            </tr>
        </thead>
        <tbody>
            {% for contact  in contacts %}
                <tr class="table-row">
                    <td class="table-cel">
                        <a href="{% url "contact:contact" contact.id %}" class="table-link">
                            {{ contact.id }}
                        </a>
                    </td>
                    <td class="table-cel">
                        {{ contact.first_name }}
                    </td>
                    <td class="table-cel">
                        {{ contact.last_name}}
                    </td>
                    <td class="table-cel">
                        {{ contact.phone}}
                    </td>
                    <td class="table-cel">
                        {{ contact.email }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}